// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unwhlerlwnlpgwkiwpbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVud2hsZXJsd25scGd3a2l3cGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjU0NTgsImV4cCI6MjA3MjU0MTQ1OH0.uX0kx_Jo6lAbOurtLNr2gSFD1-apOQkFHBv8tKsHxIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});